export const server = 'http://localhost:3000';
export const groupUrl = server + '/groups';
export const preferenceUrl = server + '/preferences';
export const readyTimetableUrl = server + '/readyTimetable' + '/5be202d4e7179a33cc149bd8' ;
export const registrationUrl = server + '/register';
export const userUrl = server + '/auth';
export const usersUrl = server + '/users'
export const calculateScheduleUrl = server + '/scheduleWork';
export const studentsUrl = server + '/students'
export const subjectsUrl = server + '/subjects'
